# Generated by Django 3.2.5 on 2021-07-03 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('age', models.IntegerField()),
                ('type', models.CharField(choices=[('1', 'Средняя'), ('2', 'Гимназия'), ('3', 'Лицей'), ('4', 'Частные'), ('5', 'Интернаты'), ('6', 'Спорт Школы')], default='Школа', max_length=255)),
            ],
        ),
    ]
