# Generated by Django 3.2.5 on 2021-07-03 06:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_teacher'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pupils',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('classes', models.CharField(max_length=255)),
                ('director', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='blog.director')),
                ('school', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='blog.school')),
            ],
        ),
    ]
