# Generated by Django 3.2.5 on 2021-07-03 06:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_pupils'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Pupils',
            new_name='Pupil',
        ),
    ]
