# Generated by Django 3.2.5 on 2021-07-06 04:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_rename_pupils_pupil'),
    ]

    operations = [
        migrations.CreateModel(
            name='Students',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('classes', models.CharField(max_length=255)),
            ],
        ),
        migrations.RenameField(
            model_name='director',
            old_name='exeriance',
            new_name='experiance',
        ),
        migrations.AddField(
            model_name='headteacher',
            name='school',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.PROTECT, to='blog.school'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='teacher',
            name='director',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.PROTECT, to='blog.director'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Pupil',
        ),
        migrations.AddField(
            model_name='students',
            name='director',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='blog.director'),
        ),
        migrations.AddField(
            model_name='students',
            name='headteacher',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='blog.headteacher'),
        ),
        migrations.AddField(
            model_name='students',
            name='school',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='blog.school'),
        ),
        migrations.AddField(
            model_name='students',
            name='teacher',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='blog.teacher'),
        ),
    ]
